<div id="about-section" class="content-section hidden">
    <h2 class="text-4xl font-bold text-gray-900 dark:text-white mb-2">About Me</h2><p class="text-orange-500 font-medium mb-8">Get to know me better</p>
    <div class="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl p-6 mb-6 shadow-sm"><p class="text-gray-600 dark:text-gray-300 leading-relaxed">I'm a <span class="text-orange-500 font-semibold">technology-driven university student</span> with a strong interest in I enjoy building structured, scalable applications — from database-driven platforms in Laravel to machine learning models deployed for real-world use. I’m particularly interested in how data and backend architecture power reliable digital systems.</p></div>
    <div class="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl p-6 mb-8 shadow-sm"><p class="text-gray-600 dark:text-gray-300 leading-relaxed">I'm an aspiring <span class="text-orange-500 font-semibold">Software Engineer</span> focused on understanding how systems work from the ground up — from databases and backend logic to APIs and user interfaces. I have also explored <span class="text-orange-500 font-semibold">machine learning model training and deployment</span>, which has strengthened my ability to think beyond just features and focus on <span class="text-orange-500 font-semibold">system design and scalability.</span></p></div>
    <h3 class="text-xl font-semibold text-gray-900 dark:text-white mb-4">What I Do</h3><div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
        <div class="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl p-5 shadow-sm hover:border-orange-500 transition-colors"><x-icon name="arrow" class="w-5 h-5 text-orange-500 mb-3" /><h4 class="font-semibold text-gray-900 dark:text-white mb-1">Backend Development</h4><p class="text-sm text-gray-500 dark:text-gray-400">Building structured, scalable systems using Laravel, MySQL, and RESTful APIs.</p></div>
        <div class="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl p-5 shadow-sm hover:border-orange-500 transition-colors"><x-icon name="monitor" class="w-5 h-5 text-orange-500 mb-3" /><h4 class="font-semibold text-gray-900 dark:text-white mb-1">Frontend & UI</h4><p class="text-sm text-gray-500 dark:text-gray-400">Crafting clean, responsive interfaces using Tailwind CSS and modern JavaScript.</p></div>
        <div class="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl p-5 shadow-sm hover:border-orange-500 transition-colors"><x-icon name="bulb" class="w-5 h-5 text-orange-500 mb-3" /><h4 class="font-semibold text-gray-900 dark:text-white mb-1">AI & Data Systems</h4><p class="text-sm text-gray-500 dark:text-gray-400">Exploring ML model training, deployment, and data-driven application development.</p></div>
    </div><div class="border-l-4 border-orange-500 pl-5 py-2"><p class="text-gray-600 dark:text-gray-300 leading-relaxed italic">"My long-term goal is to grow into a well-rounded Software Engineer capable of designing <span class="text-orange-500 font-semibold not-italic">efficient, scalable, and impactful systems</span> that solve real-world problems."</p></div>
</div>