<?php

return [
    'name' => 'Cherop Sisco',
    'job_title' => 'Junior Software Developer | Data Science & Machine Learning Enthusiast',
    'description' => 'Business Computing graduate with a strong interest in software development, data science, and machine learning. I enjoy turning ideas and real-world problems into practical technology solutions through programming, data analysis, and scalable application development.',
    'url' => env('APP_URL', 'http://localhost'),
    'image' => '/image/portfolio.jpeg',
    'location' => 'Kampala, Uganda',
    'email' => 'siscocherop668@gmail.com',
    'phone' => '+256 784 309 829 / +256 703 558 174',
    'social_links' => [
        'https://github.com/ciscocherop',
        'https://www.linkedin.com/in/sisco-cherop-193477294/',
        'https://x.com/cherryCisco',
        'https://wa.me/256703558174',
    ],
    'projects' => [
        [
            'title' => 'USSD Self-Medication System',
            'description' => 'A USSD system allowing users to connect with doctors and access health-related services. Implemented APIs, Python scripts, mobile system architecture, and database logic.',
            'url' => null,
            'tags' => ['Python', 'APIs', 'Database'],
            'type' => 'Group · Hackathon',
        ],
        [
            'title' => 'Mental Health Awareness Website — "Your Mind Matters"',
            'description' => 'A multi-page educational website promoting mental health awareness with a clean, responsive design. Led the full development process independently.',
            'url' => null,
            'tags' => ['HTML', 'CSS', 'Bootstrap'],
            'type' => 'Personal',
        ],
        [
            'title' => 'Sipi Falls Tourism Website',
            'description' => 'A dynamic tourism website promoting local tourism inspired by waterfalls from home. Full-stack development with both front-end and back-end features.',
            'url' => null,
            'tags' => ['HTML/CSS', 'JavaScript', 'PHP', 'SQL'],
            'type' => 'Personal',
        ],
        [
            'title' => "St. John's Church Management System",
            'description' => 'A web-based system to register and manage church members. Designed the dashboard, managed user registration flows, and implemented authentication features.',
            'url' => null,
            'tags' => ['Laravel', 'Tailwind CSS', 'PHP', 'SQL'],
            'type' => 'Group',
        ],
        [
            'title' => 'Autism Spectrum Disorder Prediction System',
            'description' => 'A machine learning model to predict ASD in young children using structured tabular data. Handled model deployment and participated in model training and testing.',
            'url' => null,
            'tags' => ['Python', 'Streamlit', 'Google Colab', 'ML'],
            'type' => 'Group · ML',
        ],
    ],
    'skills' => [
        [
            'heading' => 'Programming',
            'items' => [
                ['emoji' => '🐍', 'name' => 'Python', 'description' => 'Data & automation'],
                ['emoji' => '🌐', 'name' => 'JavaScript', 'description' => 'Frontend logic'],
                ['emoji' => '🐘', 'name' => 'PHP', 'description' => 'Backend apps'],
                ['emoji' => '☕', 'name' => 'Java', 'description' => 'OOP & systems'],
                ['emoji' => '🗄️', 'name' => 'SQL', 'description' => 'Database work'],
            ],
        ],
        [
            'heading' => 'Frontend & Backend',
            'items' => [
                ['emoji' => '⚛️', 'name' => 'React', 'description' => 'UI development'],
                ['emoji' => '🧩', 'name' => 'HTML5', 'description' => 'Structure & semantics'],
                ['emoji' => '🎨', 'name' => 'CSS3', 'description' => 'Styling & layout'],
                ['emoji' => '🪄', 'name' => 'Tailwind CSS', 'description' => 'Modern UI design'],
                ['emoji' => '🅱️', 'name' => 'Bootstrap', 'description' => 'Responsive design'],
                ['emoji' => '🟢', 'name' => 'Node.js', 'description' => 'Server-side JavaScript'],
                ['emoji' => '🚀', 'name' => 'Express.js', 'description' => 'API development'],
                ['emoji' => '🦁', 'name' => 'NestJS', 'description' => 'Scalable backend'],
                ['emoji' => '⚡', 'name' => 'Laravel', 'description' => 'PHP framework'],
            ],
        ],
        [
            'heading' => 'Data Science & ML',
            'items' => [
                ['emoji' => '📊', 'name' => 'Pandas', 'description' => 'Data manipulation'],
                ['emoji' => '🔢', 'name' => 'NumPy', 'description' => 'Numerical computing'],
                ['emoji' => '📈', 'name' => 'Matplotlib', 'description' => 'Visualization'],
                ['emoji' => '🧠', 'name' => 'Scikit-learn', 'description' => 'Predictive modeling'],
                ['emoji' => '🤖', 'name' => 'Machine Learning', 'description' => 'Model building'],
                ['emoji' => '📉', 'name' => 'Data Analysis', 'description' => 'Insight generation'],
                ['emoji' => '🖼️', 'name' => 'Data Visualization', 'description' => 'Storytelling with data'],
                ['emoji' => '🧬', 'name' => 'Neural Networks', 'description' => 'Deep learning basics'],
                ['emoji' => '🎛️', 'name' => 'Streamlit', 'description' => 'ML interfaces'],
            ],
        ],
        [
            'heading' => 'Databases & DevOps',
            'items' => [
                ['emoji' => '🗃️', 'name' => 'MySQL', 'description' => 'Relational data'],
                ['emoji' => '💾', 'name' => 'SQLite', 'description' => 'Lightweight storage'],
                ['emoji' => '🧰', 'name' => 'Git', 'description' => 'Version control'],
                ['emoji' => '🐙', 'name' => 'GitHub', 'description' => 'Collaboration'],
                ['emoji' => '⚙️', 'name' => 'GitHub Actions', 'description' => 'Automation'],
                ['emoji' => '🚀', 'name' => 'Vite', 'description' => 'Frontend tooling'],
                ['emoji' => '💻', 'name' => 'VS Code', 'description' => 'Development workflow'],
            ],
        ],
        [
            'heading' => 'Other Strengths',
            'items' => [
                ['emoji' => '🔌', 'name' => 'REST APIs', 'description' => 'Service integration'],
                ['emoji' => '✅', 'name' => 'Software Testing', 'description' => 'Quality assurance'],
                ['emoji' => '📐', 'name' => 'Systems Analysis', 'description' => 'Requirements and design'],
                ['emoji' => '📋', 'name' => 'IT Project Management', 'description' => 'Planning and delivery'],
                ['emoji' => '📊', 'name' => 'Business Intelligence', 'description' => 'Data-driven decisions'],
            ],
        ],
    ],
];
